version: '3.7'

services:
  server:
    build: .
    hostname: server
    container_name: Server
    networks:
      - default
  client1:
    build: .
    hostname: trainer
    container_name: Trainer
    networks:
      - default
  client2:
    build: .
    hostname: pokemon
    container_name: Pokemon
    networks:
      - default

networks:
  default:
    driver: bridge
